name: Generate Space Shooter Animation

on:
  # Runs automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"
  
  # Allows you to manually trigger it anytime
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
      
      # Generates the Space Shooter animation and pushes it to the output branch
      - name: Generate Commit Invaders
        uses: Goblinlordx/commit-invaders@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: ${{ github.repository_owner }}
